config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "trigger_event_a" => "events#trigger_event_a", as: :trigger_event_a
  get "trigger_event_b" => "events#trigger_event_b", as: :trigger_event_b

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :authenticate_user!, only: [:trigger_event_a, :trigger_event_b]
    before_action :set_iterable_service, only: [:trigger_event_a, :trigger_event_b]
    
    def index
    end
  
    def trigger_event_a
      response = @iterable_service.create_event(current_user.id, 'Event A')
      if response.success?
        flash[:notice] = "Event A created successfully!"
      else
        flash[:alert] = "Failed to create Event A."
      end
    end
  
    def trigger_event_b
      response = @iterable_service.create_event(current_user.id, 'Event B')
      if response.success?
        send_event_b_notifications
        flash[:notice] = "Event B created and notifications sent!"
      else
        flash[:alert] = "Failed to create Event B."
      end
    end
  
    private
  
    def set_iterable_service
      @iterable_service = IterableService.new()
    end
  
    def send_event_b_notifications
      events = @iterable_service.list_events(current_user.id)
      events = events.parsed_response
      events = events["events"]
      events.each do |event|
        if event['eventName'] == 'Event B'
          @iterable_service.send_email(current_user.id, 1)
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<h1>Welcome - Iterable API Mocks</h1>

<% if user_signed_in? %>
  <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'logout-link' %>
<% end %>

<h1>Create events using either one of the below two buttons</h1>

<%= button_to 'Create Event A', trigger_event_a_path, method: :get %>
<br/>
<%= button_to 'Create Event B', trigger_event_b_path, method: :get %>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IterableApiCb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>